theme: jekyll-theme-minimal
title: Design Pattern Library
logo: /assets/img/logo.jpg
description: Design pattern library to be used for stuff
show_downloads: true
links: this and another thing are links
